### ISSUE TITLE
temp/servermessage says there's a new test verion 2021-02-18 but I only see 2021-02-10 available for download?

### ISSUE THREAD

**Issue by yoyo42** [OpenScanEu/OpenScan#9]
temp/servermessage says there's a new test version 2021-02-18 but I only see 2021-02-10 available for download?

I'm testing Openscan Cloud

**Comment by Bigfellas** [comment]
I also have this issue

**Comment by OpenScanEu** [comment]
Sorry for the misconception, I use the  "servermessage" only to query the content of this: [file/page](https://raw.githubusercontent.com/OpenScanEu/OpenScan/master/temp/servermessage) as an easier way to communicate with the devices&people. I realized that in the current form only some messages make sense ^^ (i.e. I could put "server maintenance" as servermessage and as soon as it is done I will update it to a different state like "up and running").

**Comment by OpenScanEu** [comment]
By the way, I am still trying to understand github: is it ok for me to close the issue now or does the OP has do mark it as "solved" or something? (Sorry) :)
